//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  settings: Settings;
  settingsConnection: SettingsConnection;
  faq: Faq;
  faqConnection: FaqConnection;
  equipe: Equipe;
  equipeConnection: EquipeConnection;
  selections: Selections;
  selectionsConnection: SelectionsConnection;
  glossaire: Glossaire;
  glossaireConnection: GlossaireConnection;
  articles: Articles;
  articlesConnection: ArticlesConnection;
  outils: Outils;
  outilsConnection: OutilsConnection;
  secteurs: Secteurs;
  secteursConnection: SecteursConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QuerySettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};


export type QueryEquipeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEquipeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EquipeFilter>;
};


export type QuerySelectionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySelectionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SelectionsFilter>;
};


export type QueryGlossaireArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlossaireConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossaireFilter>;
};


export type QueryArticlesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArticlesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticlesFilter>;
};


export type QueryOutilsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOutilsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OutilsFilter>;
};


export type QuerySecteursArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySecteursConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SecteursFilter>;
};

export type DocumentFilter = {
  homepage?: InputMaybe<HomepageFilter>;
  settings?: InputMaybe<SettingsFilter>;
  faq?: InputMaybe<FaqFilter>;
  equipe?: InputMaybe<EquipeFilter>;
  selections?: InputMaybe<SelectionsFilter>;
  glossaire?: InputMaybe<GlossaireFilter>;
  articles?: InputMaybe<ArticlesFilter>;
  outils?: InputMaybe<OutilsFilter>;
  secteurs?: InputMaybe<SecteursFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Homepage | Settings | Faq | Equipe | Selections | Glossaire | Articles | Outils | Secteurs | Folder;

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_title?: Maybe<Scalars['String']['output']>;
  hero_subtitle?: Maybe<Scalars['String']['output']>;
  hero_cta_primary?: Maybe<Scalars['String']['output']>;
  hero_cta_secondary?: Maybe<Scalars['String']['output']>;
  transparency_text?: Maybe<Scalars['String']['output']>;
  section_outils_title?: Maybe<Scalars['String']['output']>;
  section_outils_subtitle?: Maybe<Scalars['String']['output']>;
  section_blog_title?: Maybe<Scalars['String']['output']>;
  section_blog_subtitle?: Maybe<Scalars['String']['output']>;
  newsletter_title?: Maybe<Scalars['String']['output']>;
  newsletter_subtitle?: Maybe<Scalars['String']['output']>;
  newsletter_cta?: Maybe<Scalars['String']['output']>;
  announcement_enabled?: Maybe<Scalars['Boolean']['output']>;
  announcement_text?: Maybe<Scalars['String']['output']>;
  announcement_url?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HomepageFilter = {
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_title?: InputMaybe<StringFilter>;
  hero_subtitle?: InputMaybe<StringFilter>;
  hero_cta_primary?: InputMaybe<StringFilter>;
  hero_cta_secondary?: InputMaybe<StringFilter>;
  transparency_text?: InputMaybe<StringFilter>;
  section_outils_title?: InputMaybe<StringFilter>;
  section_outils_subtitle?: InputMaybe<StringFilter>;
  section_blog_title?: InputMaybe<StringFilter>;
  section_blog_subtitle?: InputMaybe<StringFilter>;
  newsletter_title?: InputMaybe<StringFilter>;
  newsletter_subtitle?: InputMaybe<StringFilter>;
  newsletter_cta?: InputMaybe<StringFilter>;
  announcement_enabled?: InputMaybe<BooleanFilter>;
  announcement_text?: InputMaybe<StringFilter>;
  announcement_url?: InputMaybe<StringFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Settings = Node & Document & {
  __typename?: 'Settings';
  site_name?: Maybe<Scalars['String']['output']>;
  site_tagline?: Maybe<Scalars['String']['output']>;
  site_url?: Maybe<Scalars['String']['output']>;
  site_description?: Maybe<Scalars['String']['output']>;
  og_image?: Maybe<Scalars['String']['output']>;
  footer_tagline?: Maybe<Scalars['String']['output']>;
  footer_copyright?: Maybe<Scalars['String']['output']>;
  footer_baseline?: Maybe<Scalars['String']['output']>;
  nav_cta_ghost?: Maybe<Scalars['String']['output']>;
  nav_cta_ghost_href?: Maybe<Scalars['String']['output']>;
  nav_cta_primary?: Maybe<Scalars['String']['output']>;
  nav_cta_primary_href?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SettingsFilter = {
  site_name?: InputMaybe<StringFilter>;
  site_tagline?: InputMaybe<StringFilter>;
  site_url?: InputMaybe<StringFilter>;
  site_description?: InputMaybe<StringFilter>;
  og_image?: InputMaybe<ImageFilter>;
  footer_tagline?: InputMaybe<StringFilter>;
  footer_copyright?: InputMaybe<StringFilter>;
  footer_baseline?: InputMaybe<StringFilter>;
  nav_cta_ghost?: InputMaybe<StringFilter>;
  nav_cta_ghost_href?: InputMaybe<StringFilter>;
  nav_cta_primary?: InputMaybe<StringFilter>;
  nav_cta_primary_href?: InputMaybe<StringFilter>;
};

export type SettingsConnectionEdges = {
  __typename?: 'SettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Settings>;
};

export type SettingsConnection = Connection & {
  __typename?: 'SettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SettingsConnectionEdges>>>;
};

export type FaqFaqs = {
  __typename?: 'FaqFaqs';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  faqs?: Maybe<Array<Maybe<FaqFaqs>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type FaqFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<FaqFaqsFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type EquipeMembers = {
  __typename?: 'EquipeMembers';
  name?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  avatar?: Maybe<Scalars['String']['output']>;
};

export type EquipeValues = {
  __typename?: 'EquipeValues';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Equipe = Node & Document & {
  __typename?: 'Equipe';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  members?: Maybe<Array<Maybe<EquipeMembers>>>;
  values?: Maybe<Array<Maybe<EquipeValues>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EquipeMembersFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  avatar?: InputMaybe<ImageFilter>;
};

export type EquipeValuesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type EquipeFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  members?: InputMaybe<EquipeMembersFilter>;
  values?: InputMaybe<EquipeValuesFilter>;
};

export type EquipeConnectionEdges = {
  __typename?: 'EquipeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Equipe>;
};

export type EquipeConnection = Connection & {
  __typename?: 'EquipeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EquipeConnectionEdges>>>;
};

export type Selections = Node & Document & {
  __typename?: 'Selections';
  slug: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  coverPhoto?: Maybe<Scalars['String']['output']>;
  coverAlt?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  outils?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SelectionsFilter = {
  slug?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  coverPhoto?: InputMaybe<ImageFilter>;
  coverAlt?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  outils?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type SelectionsConnectionEdges = {
  __typename?: 'SelectionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Selections>;
};

export type SelectionsConnection = Connection & {
  __typename?: 'SelectionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SelectionsConnectionEdges>>>;
};

export type GlossaireTerms = {
  __typename?: 'GlossaireTerms';
  term?: Maybe<Scalars['String']['output']>;
  definition?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Glossaire = Node & Document & {
  __typename?: 'Glossaire';
  terms?: Maybe<Array<Maybe<GlossaireTerms>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlossaireTermsFilter = {
  term?: InputMaybe<StringFilter>;
  definition?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
};

export type GlossaireFilter = {
  terms?: InputMaybe<GlossaireTermsFilter>;
};

export type GlossaireConnectionEdges = {
  __typename?: 'GlossaireConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Glossaire>;
};

export type GlossaireConnection = Connection & {
  __typename?: 'GlossaireConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlossaireConnectionEdges>>>;
};

export type ArticlesSections = {
  __typename?: 'ArticlesSections';
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
};

export type ArticlesFaq = {
  __typename?: 'ArticlesFaq';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
};

export type Articles = Node & Document & {
  __typename?: 'Articles';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  sectorLabel?: Maybe<Scalars['String']['output']>;
  sector?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  coverPhoto?: Maybe<Scalars['String']['output']>;
  coverAlt?: Maybe<Scalars['String']['output']>;
  metaDescription?: Maybe<Scalars['String']['output']>;
  keywordTarget?: Maybe<Scalars['String']['output']>;
  intro?: Maybe<Scalars['String']['output']>;
  pullQuote?: Maybe<Scalars['String']['output']>;
  sections?: Maybe<Array<Maybe<ArticlesSections>>>;
  faq?: Maybe<Array<Maybe<ArticlesFaq>>>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArticlesSectionsFilter = {
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArticlesFaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type ArticlesFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  sectorLabel?: InputMaybe<StringFilter>;
  sector?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  coverPhoto?: InputMaybe<ImageFilter>;
  coverAlt?: InputMaybe<StringFilter>;
  metaDescription?: InputMaybe<StringFilter>;
  keywordTarget?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  pullQuote?: InputMaybe<StringFilter>;
  sections?: InputMaybe<ArticlesSectionsFilter>;
  faq?: InputMaybe<ArticlesFaqFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type ArticlesConnectionEdges = {
  __typename?: 'ArticlesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Articles>;
};

export type ArticlesConnection = Connection & {
  __typename?: 'ArticlesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArticlesConnectionEdges>>>;
};

export type Outils = Node & Document & {
  __typename?: 'Outils';
  identifiant: Scalars['String']['output'];
  name: Scalars['String']['output'];
  tagline?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  sector?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  priceDetails?: Maybe<Scalars['String']['output']>;
  priceType?: Maybe<Scalars['String']['output']>;
  badge?: Maybe<Scalars['String']['output']>;
  badgeLabel?: Maybe<Scalars['String']['output']>;
  apiReady?: Maybe<Scalars['Boolean']['output']>;
  tested?: Maybe<Scalars['Boolean']['output']>;
  score?: Maybe<Scalars['Float']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  description?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  useCases?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type OutilsFilter = {
  identifiant?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  sector?: InputMaybe<StringFilter>;
  priceDetails?: InputMaybe<StringFilter>;
  priceType?: InputMaybe<StringFilter>;
  badge?: InputMaybe<StringFilter>;
  badgeLabel?: InputMaybe<StringFilter>;
  apiReady?: InputMaybe<BooleanFilter>;
  tested?: InputMaybe<BooleanFilter>;
  score?: InputMaybe<NumberFilter>;
  logo?: InputMaybe<ImageFilter>;
  url?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  features?: InputMaybe<StringFilter>;
  useCases?: InputMaybe<StringFilter>;
};

export type OutilsConnectionEdges = {
  __typename?: 'OutilsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Outils>;
};

export type OutilsConnection = Connection & {
  __typename?: 'OutilsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OutilsConnectionEdges>>>;
};

export type Secteurs = Node & Document & {
  __typename?: 'Secteurs';
  identifiant: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
  photo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SecteursFilter = {
  identifiant?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
};

export type SecteursConnectionEdges = {
  __typename?: 'SecteursConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Secteurs>;
};

export type SecteursConnection = Connection & {
  __typename?: 'SecteursConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SecteursConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateSettings: Settings;
  createSettings: Settings;
  updateFaq: Faq;
  createFaq: Faq;
  updateEquipe: Equipe;
  createEquipe: Equipe;
  updateSelections: Selections;
  createSelections: Selections;
  updateGlossaire: Glossaire;
  createGlossaire: Glossaire;
  updateArticles: Articles;
  createArticles: Articles;
  updateOutils: Outils;
  createOutils: Outils;
  updateSecteurs: Secteurs;
  createSecteurs: Secteurs;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationCreateSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SettingsMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationUpdateEquipeArgs = {
  relativePath: Scalars['String']['input'];
  params: EquipeMutation;
};


export type MutationCreateEquipeArgs = {
  relativePath: Scalars['String']['input'];
  params: EquipeMutation;
};


export type MutationUpdateSelectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: SelectionsMutation;
};


export type MutationCreateSelectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: SelectionsMutation;
};


export type MutationUpdateGlossaireArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossaireMutation;
};


export type MutationCreateGlossaireArgs = {
  relativePath: Scalars['String']['input'];
  params: GlossaireMutation;
};


export type MutationUpdateArticlesArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticlesMutation;
};


export type MutationCreateArticlesArgs = {
  relativePath: Scalars['String']['input'];
  params: ArticlesMutation;
};


export type MutationUpdateOutilsArgs = {
  relativePath: Scalars['String']['input'];
  params: OutilsMutation;
};


export type MutationCreateOutilsArgs = {
  relativePath: Scalars['String']['input'];
  params: OutilsMutation;
};


export type MutationUpdateSecteursArgs = {
  relativePath: Scalars['String']['input'];
  params: SecteursMutation;
};


export type MutationCreateSecteursArgs = {
  relativePath: Scalars['String']['input'];
  params: SecteursMutation;
};

export type DocumentUpdateMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  settings?: InputMaybe<SettingsMutation>;
  faq?: InputMaybe<FaqMutation>;
  equipe?: InputMaybe<EquipeMutation>;
  selections?: InputMaybe<SelectionsMutation>;
  glossaire?: InputMaybe<GlossaireMutation>;
  articles?: InputMaybe<ArticlesMutation>;
  outils?: InputMaybe<OutilsMutation>;
  secteurs?: InputMaybe<SecteursMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  settings?: InputMaybe<SettingsMutation>;
  faq?: InputMaybe<FaqMutation>;
  equipe?: InputMaybe<EquipeMutation>;
  selections?: InputMaybe<SelectionsMutation>;
  glossaire?: InputMaybe<GlossaireMutation>;
  articles?: InputMaybe<ArticlesMutation>;
  outils?: InputMaybe<OutilsMutation>;
  secteurs?: InputMaybe<SecteursMutation>;
};

export type HomepageMutation = {
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_title?: InputMaybe<Scalars['String']['input']>;
  hero_subtitle?: InputMaybe<Scalars['String']['input']>;
  hero_cta_primary?: InputMaybe<Scalars['String']['input']>;
  hero_cta_secondary?: InputMaybe<Scalars['String']['input']>;
  transparency_text?: InputMaybe<Scalars['String']['input']>;
  section_outils_title?: InputMaybe<Scalars['String']['input']>;
  section_outils_subtitle?: InputMaybe<Scalars['String']['input']>;
  section_blog_title?: InputMaybe<Scalars['String']['input']>;
  section_blog_subtitle?: InputMaybe<Scalars['String']['input']>;
  newsletter_title?: InputMaybe<Scalars['String']['input']>;
  newsletter_subtitle?: InputMaybe<Scalars['String']['input']>;
  newsletter_cta?: InputMaybe<Scalars['String']['input']>;
  announcement_enabled?: InputMaybe<Scalars['Boolean']['input']>;
  announcement_text?: InputMaybe<Scalars['String']['input']>;
  announcement_url?: InputMaybe<Scalars['String']['input']>;
};

export type SettingsMutation = {
  site_name?: InputMaybe<Scalars['String']['input']>;
  site_tagline?: InputMaybe<Scalars['String']['input']>;
  site_url?: InputMaybe<Scalars['String']['input']>;
  site_description?: InputMaybe<Scalars['String']['input']>;
  og_image?: InputMaybe<Scalars['String']['input']>;
  footer_tagline?: InputMaybe<Scalars['String']['input']>;
  footer_copyright?: InputMaybe<Scalars['String']['input']>;
  footer_baseline?: InputMaybe<Scalars['String']['input']>;
  nav_cta_ghost?: InputMaybe<Scalars['String']['input']>;
  nav_cta_ghost_href?: InputMaybe<Scalars['String']['input']>;
  nav_cta_primary?: InputMaybe<Scalars['String']['input']>;
  nav_cta_primary_href?: InputMaybe<Scalars['String']['input']>;
};

export type FaqFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type FaqMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  faqs?: InputMaybe<Array<InputMaybe<FaqFaqsMutation>>>;
};

export type EquipeMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  avatar?: InputMaybe<Scalars['String']['input']>;
};

export type EquipeValuesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type EquipeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  members?: InputMaybe<Array<InputMaybe<EquipeMembersMutation>>>;
  values?: InputMaybe<Array<InputMaybe<EquipeValuesMutation>>>;
};

export type SelectionsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  coverPhoto?: InputMaybe<Scalars['String']['input']>;
  coverAlt?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  outils?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type GlossaireTermsMutation = {
  term?: InputMaybe<Scalars['String']['input']>;
  definition?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type GlossaireMutation = {
  terms?: InputMaybe<Array<InputMaybe<GlossaireTermsMutation>>>;
};

export type ArticlesSectionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArticlesFaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type ArticlesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  sectorLabel?: InputMaybe<Scalars['String']['input']>;
  sector?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  coverPhoto?: InputMaybe<Scalars['String']['input']>;
  coverAlt?: InputMaybe<Scalars['String']['input']>;
  metaDescription?: InputMaybe<Scalars['String']['input']>;
  keywordTarget?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  pullQuote?: InputMaybe<Scalars['String']['input']>;
  sections?: InputMaybe<Array<InputMaybe<ArticlesSectionsMutation>>>;
  faq?: InputMaybe<Array<InputMaybe<ArticlesFaqMutation>>>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type OutilsMutation = {
  identifiant?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  sector?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  priceDetails?: InputMaybe<Scalars['String']['input']>;
  priceType?: InputMaybe<Scalars['String']['input']>;
  badge?: InputMaybe<Scalars['String']['input']>;
  badgeLabel?: InputMaybe<Scalars['String']['input']>;
  apiReady?: InputMaybe<Scalars['Boolean']['input']>;
  tested?: InputMaybe<Scalars['Boolean']['input']>;
  score?: InputMaybe<Scalars['Float']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  description?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  useCases?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SecteursMutation = {
  identifiant?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
};

export type HomepagePartsFragment = { __typename: 'Homepage', hero_eyebrow?: string | null, hero_title?: string | null, hero_subtitle?: string | null, hero_cta_primary?: string | null, hero_cta_secondary?: string | null, transparency_text?: string | null, section_outils_title?: string | null, section_outils_subtitle?: string | null, section_blog_title?: string | null, section_blog_subtitle?: string | null, newsletter_title?: string | null, newsletter_subtitle?: string | null, newsletter_cta?: string | null, announcement_enabled?: boolean | null, announcement_text?: string | null, announcement_url?: string | null };

export type SettingsPartsFragment = { __typename: 'Settings', site_name?: string | null, site_tagline?: string | null, site_url?: string | null, site_description?: string | null, og_image?: string | null, footer_tagline?: string | null, footer_copyright?: string | null, footer_baseline?: string | null, nav_cta_ghost?: string | null, nav_cta_ghost_href?: string | null, nav_cta_primary?: string | null, nav_cta_primary_href?: string | null };

export type FaqPartsFragment = { __typename: 'Faq', title: string, subtitle?: string | null, faqs?: Array<{ __typename: 'FaqFaqs', question?: string | null, answer?: string | null } | null> | null };

export type EquipePartsFragment = { __typename: 'Equipe', title: string, subtitle?: string | null, intro?: string | null, members?: Array<{ __typename: 'EquipeMembers', name?: string | null, role?: string | null, bio?: string | null, avatar?: string | null } | null> | null, values?: Array<{ __typename: 'EquipeValues', title?: string | null, description?: string | null } | null> | null };

export type SelectionsPartsFragment = { __typename: 'Selections', slug: string, title: string, description?: string | null, coverPhoto?: string | null, coverAlt?: string | null, metaDescription?: string | null, date?: string | null, intro?: string | null, outils?: Array<string | null> | null, tags?: Array<string | null> | null };

export type GlossairePartsFragment = { __typename: 'Glossaire', terms?: Array<{ __typename: 'GlossaireTerms', term?: string | null, definition?: string | null, category?: string | null } | null> | null };

export type ArticlesPartsFragment = { __typename: 'Articles', title: string, slug: string, sectorLabel?: string | null, sector?: string | null, readTime?: string | null, date?: string | null, coverPhoto?: string | null, coverAlt?: string | null, metaDescription?: string | null, keywordTarget?: string | null, intro?: string | null, pullQuote?: string | null, tags?: Array<string | null> | null, sections?: Array<{ __typename: 'ArticlesSections', title?: string | null, body?: any | null } | null> | null, faq?: Array<{ __typename: 'ArticlesFaq', question?: string | null, answer?: string | null } | null> | null };

export type OutilsPartsFragment = { __typename: 'Outils', identifiant: string, name: string, tagline?: string | null, category?: string | null, sector?: Array<string | null> | null, priceDetails?: string | null, priceType?: string | null, badge?: string | null, badgeLabel?: string | null, apiReady?: boolean | null, tested?: boolean | null, score?: number | null, logo?: string | null, url?: string | null, tags?: Array<string | null> | null, description?: string | null, features?: Array<string | null> | null, useCases?: Array<string | null> | null };

export type SecteursPartsFragment = { __typename: 'Secteurs', identifiant: string, label?: string | null, headline?: string | null, sub?: string | null, photo?: string | null };

export type HomepageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomepageQuery = { __typename?: 'Query', homepage: { __typename: 'Homepage', id: string, hero_eyebrow?: string | null, hero_title?: string | null, hero_subtitle?: string | null, hero_cta_primary?: string | null, hero_cta_secondary?: string | null, transparency_text?: string | null, section_outils_title?: string | null, section_outils_subtitle?: string | null, section_blog_title?: string | null, section_blog_subtitle?: string | null, newsletter_title?: string | null, newsletter_subtitle?: string | null, newsletter_cta?: string | null, announcement_enabled?: boolean | null, announcement_text?: string | null, announcement_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
}>;


export type HomepageConnectionQuery = { __typename?: 'Query', homepageConnection: { __typename?: 'HomepageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomepageConnectionEdges', cursor: string, node?: { __typename: 'Homepage', id: string, hero_eyebrow?: string | null, hero_title?: string | null, hero_subtitle?: string | null, hero_cta_primary?: string | null, hero_cta_secondary?: string | null, transparency_text?: string | null, section_outils_title?: string | null, section_outils_subtitle?: string | null, section_blog_title?: string | null, section_blog_subtitle?: string | null, newsletter_title?: string | null, newsletter_subtitle?: string | null, newsletter_cta?: string | null, announcement_enabled?: boolean | null, announcement_text?: string | null, announcement_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SettingsQuery = { __typename?: 'Query', settings: { __typename: 'Settings', id: string, site_name?: string | null, site_tagline?: string | null, site_url?: string | null, site_description?: string | null, og_image?: string | null, footer_tagline?: string | null, footer_copyright?: string | null, footer_baseline?: string | null, nav_cta_ghost?: string | null, nav_cta_ghost_href?: string | null, nav_cta_primary?: string | null, nav_cta_primary_href?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SettingsFilter>;
}>;


export type SettingsConnectionQuery = { __typename?: 'Query', settingsConnection: { __typename?: 'SettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SettingsConnectionEdges', cursor: string, node?: { __typename: 'Settings', id: string, site_name?: string | null, site_tagline?: string | null, site_url?: string | null, site_description?: string | null, og_image?: string | null, footer_tagline?: string | null, footer_copyright?: string | null, footer_baseline?: string | null, nav_cta_ghost?: string | null, nav_cta_ghost_href?: string | null, nav_cta_primary?: string | null, nav_cta_primary_href?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqQuery = { __typename?: 'Query', faq: { __typename: 'Faq', id: string, title: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'FaqFaqs', question?: string | null, answer?: string | null } | null> | null } };

export type FaqConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
}>;


export type FaqConnectionQuery = { __typename?: 'Query', faqConnection: { __typename?: 'FaqConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqConnectionEdges', cursor: string, node?: { __typename: 'Faq', id: string, title: string, subtitle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'FaqFaqs', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export type EquipeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EquipeQuery = { __typename?: 'Query', equipe: { __typename: 'Equipe', id: string, title: string, subtitle?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'EquipeMembers', name?: string | null, role?: string | null, bio?: string | null, avatar?: string | null } | null> | null, values?: Array<{ __typename: 'EquipeValues', title?: string | null, description?: string | null } | null> | null } };

export type EquipeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EquipeFilter>;
}>;


export type EquipeConnectionQuery = { __typename?: 'Query', equipeConnection: { __typename?: 'EquipeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EquipeConnectionEdges', cursor: string, node?: { __typename: 'Equipe', id: string, title: string, subtitle?: string | null, intro?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, members?: Array<{ __typename: 'EquipeMembers', name?: string | null, role?: string | null, bio?: string | null, avatar?: string | null } | null> | null, values?: Array<{ __typename: 'EquipeValues', title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type SelectionsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SelectionsQuery = { __typename?: 'Query', selections: { __typename: 'Selections', id: string, slug: string, title: string, description?: string | null, coverPhoto?: string | null, coverAlt?: string | null, metaDescription?: string | null, date?: string | null, intro?: string | null, outils?: Array<string | null> | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SelectionsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SelectionsFilter>;
}>;


export type SelectionsConnectionQuery = { __typename?: 'Query', selectionsConnection: { __typename?: 'SelectionsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SelectionsConnectionEdges', cursor: string, node?: { __typename: 'Selections', id: string, slug: string, title: string, description?: string | null, coverPhoto?: string | null, coverAlt?: string | null, metaDescription?: string | null, date?: string | null, intro?: string | null, outils?: Array<string | null> | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GlossaireQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlossaireQuery = { __typename?: 'Query', glossaire: { __typename: 'Glossaire', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, terms?: Array<{ __typename: 'GlossaireTerms', term?: string | null, definition?: string | null, category?: string | null } | null> | null } };

export type GlossaireConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlossaireFilter>;
}>;


export type GlossaireConnectionQuery = { __typename?: 'Query', glossaireConnection: { __typename?: 'GlossaireConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlossaireConnectionEdges', cursor: string, node?: { __typename: 'Glossaire', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, terms?: Array<{ __typename: 'GlossaireTerms', term?: string | null, definition?: string | null, category?: string | null } | null> | null } | null } | null> | null } };

export type ArticlesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArticlesQuery = { __typename?: 'Query', articles: { __typename: 'Articles', id: string, title: string, slug: string, sectorLabel?: string | null, sector?: string | null, readTime?: string | null, date?: string | null, coverPhoto?: string | null, coverAlt?: string | null, metaDescription?: string | null, keywordTarget?: string | null, intro?: string | null, pullQuote?: string | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'ArticlesSections', title?: string | null, body?: any | null } | null> | null, faq?: Array<{ __typename: 'ArticlesFaq', question?: string | null, answer?: string | null } | null> | null } };

export type ArticlesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArticlesFilter>;
}>;


export type ArticlesConnectionQuery = { __typename?: 'Query', articlesConnection: { __typename?: 'ArticlesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArticlesConnectionEdges', cursor: string, node?: { __typename: 'Articles', id: string, title: string, slug: string, sectorLabel?: string | null, sector?: string | null, readTime?: string | null, date?: string | null, coverPhoto?: string | null, coverAlt?: string | null, metaDescription?: string | null, keywordTarget?: string | null, intro?: string | null, pullQuote?: string | null, tags?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, sections?: Array<{ __typename: 'ArticlesSections', title?: string | null, body?: any | null } | null> | null, faq?: Array<{ __typename: 'ArticlesFaq', question?: string | null, answer?: string | null } | null> | null } | null } | null> | null } };

export type OutilsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type OutilsQuery = { __typename?: 'Query', outils: { __typename: 'Outils', id: string, identifiant: string, name: string, tagline?: string | null, category?: string | null, sector?: Array<string | null> | null, priceDetails?: string | null, priceType?: string | null, badge?: string | null, badgeLabel?: string | null, apiReady?: boolean | null, tested?: boolean | null, score?: number | null, logo?: string | null, url?: string | null, tags?: Array<string | null> | null, description?: string | null, features?: Array<string | null> | null, useCases?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type OutilsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OutilsFilter>;
}>;


export type OutilsConnectionQuery = { __typename?: 'Query', outilsConnection: { __typename?: 'OutilsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'OutilsConnectionEdges', cursor: string, node?: { __typename: 'Outils', id: string, identifiant: string, name: string, tagline?: string | null, category?: string | null, sector?: Array<string | null> | null, priceDetails?: string | null, priceType?: string | null, badge?: string | null, badgeLabel?: string | null, apiReady?: boolean | null, tested?: boolean | null, score?: number | null, logo?: string | null, url?: string | null, tags?: Array<string | null> | null, description?: string | null, features?: Array<string | null> | null, useCases?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SecteursQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SecteursQuery = { __typename?: 'Query', secteurs: { __typename: 'Secteurs', id: string, identifiant: string, label?: string | null, headline?: string | null, sub?: string | null, photo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SecteursConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SecteursFilter>;
}>;


export type SecteursConnectionQuery = { __typename?: 'Query', secteursConnection: { __typename?: 'SecteursConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SecteursConnectionEdges', cursor: string, node?: { __typename: 'Secteurs', id: string, identifiant: string, label?: string | null, headline?: string | null, sub?: string | null, photo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  hero_eyebrow
  hero_title
  hero_subtitle
  hero_cta_primary
  hero_cta_secondary
  transparency_text
  section_outils_title
  section_outils_subtitle
  section_blog_title
  section_blog_subtitle
  newsletter_title
  newsletter_subtitle
  newsletter_cta
  announcement_enabled
  announcement_text
  announcement_url
}
    `;
export const SettingsPartsFragmentDoc = gql`
    fragment SettingsParts on Settings {
  __typename
  site_name
  site_tagline
  site_url
  site_description
  og_image
  footer_tagline
  footer_copyright
  footer_baseline
  nav_cta_ghost
  nav_cta_ghost_href
  nav_cta_primary
  nav_cta_primary_href
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  title
  subtitle
  faqs {
    __typename
    question
    answer
  }
}
    `;
export const EquipePartsFragmentDoc = gql`
    fragment EquipeParts on Equipe {
  __typename
  title
  subtitle
  intro
  members {
    __typename
    name
    role
    bio
    avatar
  }
  values {
    __typename
    title
    description
  }
}
    `;
export const SelectionsPartsFragmentDoc = gql`
    fragment SelectionsParts on Selections {
  __typename
  slug
  title
  description
  coverPhoto
  coverAlt
  metaDescription
  date
  intro
  outils
  tags
}
    `;
export const GlossairePartsFragmentDoc = gql`
    fragment GlossaireParts on Glossaire {
  __typename
  terms {
    __typename
    term
    definition
    category
  }
}
    `;
export const ArticlesPartsFragmentDoc = gql`
    fragment ArticlesParts on Articles {
  __typename
  title
  slug
  sectorLabel
  sector
  readTime
  date
  coverPhoto
  coverAlt
  metaDescription
  keywordTarget
  intro
  pullQuote
  sections {
    __typename
    title
    body
  }
  faq {
    __typename
    question
    answer
  }
  tags
}
    `;
export const OutilsPartsFragmentDoc = gql`
    fragment OutilsParts on Outils {
  __typename
  identifiant
  name
  tagline
  category
  sector
  priceDetails
  priceType
  badge
  badgeLabel
  apiReady
  tested
  score
  logo
  url
  tags
  description
  features
  useCases
}
    `;
export const SecteursPartsFragmentDoc = gql`
    fragment SecteursParts on Secteurs {
  __typename
  identifiant
  label
  headline
  sub
  photo
}
    `;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const SettingsDocument = gql`
    query settings($relativePath: String!) {
  settings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SettingsParts
  }
}
    ${SettingsPartsFragmentDoc}`;
export const SettingsConnectionDocument = gql`
    query settingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SettingsFilter) {
  settingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SettingsParts
      }
    }
  }
}
    ${SettingsPartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export const EquipeDocument = gql`
    query equipe($relativePath: String!) {
  equipe(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EquipeParts
  }
}
    ${EquipePartsFragmentDoc}`;
export const EquipeConnectionDocument = gql`
    query equipeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EquipeFilter) {
  equipeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EquipeParts
      }
    }
  }
}
    ${EquipePartsFragmentDoc}`;
export const SelectionsDocument = gql`
    query selections($relativePath: String!) {
  selections(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SelectionsParts
  }
}
    ${SelectionsPartsFragmentDoc}`;
export const SelectionsConnectionDocument = gql`
    query selectionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SelectionsFilter) {
  selectionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SelectionsParts
      }
    }
  }
}
    ${SelectionsPartsFragmentDoc}`;
export const GlossaireDocument = gql`
    query glossaire($relativePath: String!) {
  glossaire(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlossaireParts
  }
}
    ${GlossairePartsFragmentDoc}`;
export const GlossaireConnectionDocument = gql`
    query glossaireConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlossaireFilter) {
  glossaireConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlossaireParts
      }
    }
  }
}
    ${GlossairePartsFragmentDoc}`;
export const ArticlesDocument = gql`
    query articles($relativePath: String!) {
  articles(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArticlesParts
  }
}
    ${ArticlesPartsFragmentDoc}`;
export const ArticlesConnectionDocument = gql`
    query articlesConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArticlesFilter) {
  articlesConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArticlesParts
      }
    }
  }
}
    ${ArticlesPartsFragmentDoc}`;
export const OutilsDocument = gql`
    query outils($relativePath: String!) {
  outils(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OutilsParts
  }
}
    ${OutilsPartsFragmentDoc}`;
export const OutilsConnectionDocument = gql`
    query outilsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OutilsFilter) {
  outilsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OutilsParts
      }
    }
  }
}
    ${OutilsPartsFragmentDoc}`;
export const SecteursDocument = gql`
    query secteurs($relativePath: String!) {
  secteurs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SecteursParts
  }
}
    ${SecteursPartsFragmentDoc}`;
export const SecteursConnectionDocument = gql`
    query secteursConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SecteursFilter) {
  secteursConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SecteursParts
      }
    }
  }
}
    ${SecteursPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    settings(variables: SettingsQueryVariables, options?: C): Promise<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}> {
        return requester<{data: SettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsQueryVariables, query: string}, SettingsQueryVariables>(SettingsDocument, variables, options);
      },
    settingsConnection(variables?: SettingsConnectionQueryVariables, options?: C): Promise<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SettingsConnectionQueryVariables, query: string}, SettingsConnectionQueryVariables>(SettingsConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      },
    equipe(variables: EquipeQueryVariables, options?: C): Promise<{data: EquipeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipeQueryVariables, query: string}> {
        return requester<{data: EquipeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipeQueryVariables, query: string}, EquipeQueryVariables>(EquipeDocument, variables, options);
      },
    equipeConnection(variables?: EquipeConnectionQueryVariables, options?: C): Promise<{data: EquipeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipeConnectionQueryVariables, query: string}> {
        return requester<{data: EquipeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EquipeConnectionQueryVariables, query: string}, EquipeConnectionQueryVariables>(EquipeConnectionDocument, variables, options);
      },
    selections(variables: SelectionsQueryVariables, options?: C): Promise<{data: SelectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SelectionsQueryVariables, query: string}> {
        return requester<{data: SelectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SelectionsQueryVariables, query: string}, SelectionsQueryVariables>(SelectionsDocument, variables, options);
      },
    selectionsConnection(variables?: SelectionsConnectionQueryVariables, options?: C): Promise<{data: SelectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SelectionsConnectionQueryVariables, query: string}> {
        return requester<{data: SelectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SelectionsConnectionQueryVariables, query: string}, SelectionsConnectionQueryVariables>(SelectionsConnectionDocument, variables, options);
      },
    glossaire(variables: GlossaireQueryVariables, options?: C): Promise<{data: GlossaireQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaireQueryVariables, query: string}> {
        return requester<{data: GlossaireQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaireQueryVariables, query: string}, GlossaireQueryVariables>(GlossaireDocument, variables, options);
      },
    glossaireConnection(variables?: GlossaireConnectionQueryVariables, options?: C): Promise<{data: GlossaireConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaireConnectionQueryVariables, query: string}> {
        return requester<{data: GlossaireConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlossaireConnectionQueryVariables, query: string}, GlossaireConnectionQueryVariables>(GlossaireConnectionDocument, variables, options);
      },
    articles(variables: ArticlesQueryVariables, options?: C): Promise<{data: ArticlesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesQueryVariables, query: string}> {
        return requester<{data: ArticlesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesQueryVariables, query: string}, ArticlesQueryVariables>(ArticlesDocument, variables, options);
      },
    articlesConnection(variables?: ArticlesConnectionQueryVariables, options?: C): Promise<{data: ArticlesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesConnectionQueryVariables, query: string}> {
        return requester<{data: ArticlesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArticlesConnectionQueryVariables, query: string}, ArticlesConnectionQueryVariables>(ArticlesConnectionDocument, variables, options);
      },
    outils(variables: OutilsQueryVariables, options?: C): Promise<{data: OutilsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutilsQueryVariables, query: string}> {
        return requester<{data: OutilsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutilsQueryVariables, query: string}, OutilsQueryVariables>(OutilsDocument, variables, options);
      },
    outilsConnection(variables?: OutilsConnectionQueryVariables, options?: C): Promise<{data: OutilsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutilsConnectionQueryVariables, query: string}> {
        return requester<{data: OutilsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OutilsConnectionQueryVariables, query: string}, OutilsConnectionQueryVariables>(OutilsConnectionDocument, variables, options);
      },
    secteurs(variables: SecteursQueryVariables, options?: C): Promise<{data: SecteursQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SecteursQueryVariables, query: string}> {
        return requester<{data: SecteursQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SecteursQueryVariables, query: string}, SecteursQueryVariables>(SecteursDocument, variables, options);
      },
    secteursConnection(variables?: SecteursConnectionQueryVariables, options?: C): Promise<{data: SecteursConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SecteursConnectionQueryVariables, query: string}> {
        return requester<{data: SecteursConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SecteursConnectionQueryVariables, query: string}, SecteursConnectionQueryVariables>(SecteursConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  